version: 2
jobs:
  bootstrap-build:
    docker:
      - image: codesmithy/gcc-bootstrap-build-prerequisites:0.1.0
    steps:
      - run: 
          name: "Set CODESMITHYIDE environment variables"
          command: echo 'export CODESMITHYIDE="/CodeSmithyIDE"' >> $BASH_ENV
      - checkout:
          path: /CodeSmithyIDE/BuildToolchains
      - run:
          name: Build
          command: cd /CodeSmithyIDE/BuildToolchains/Makefiles/GNUmakefile && make
  build:
    docker:
      - image: codesmithy/gcc-build-prerequisites:0.1.0
    steps:
      - run:
          name: "Set CODESMITHYIDE environment variables"
          command: echo 'export CODESMITHYIDE="/CodeSmithyIDE"' >> $BASH_ENV
      - checkout:
          path: /CodeSmithyIDE/BuildToolchains
      - run:
          name: Build
          command: cd /CodeSmithyIDE/BuildToolchains/Makefiles/GNUmakefile && make
workflows:
  version: 2
  build:
    jobs:
      - bootstrap-build
      - build
