version: 2
jobs:
  bootstrap-build:
    docker:
      - image: codesmithy/gcc-bootstrap-build-prerequisites:0.1.0
    steps:
      - run: 
          name: "Set CODESMITHYIDE environment variables"
          command: echo 'export CODESMITHYIDE="/codesmithyide"' >> $BASH_ENV
      - checkout:
          path: /codesmithyide/build-toolchains
      - run:
          name: Build
          command: cd /codesmithyide/build-toolchains/build/GNUmakefile && make
      - run:
          name: Test build
          command: cd /codesmithyide/build-toolchains/Tests/Makefiles/GNUmakefile && make
      - run:
          name: Run the tests
          command: cd /codesmithyide/build-toolchains/Tests/Makefiles/GNUmakefile && ./CodeSmithyBuildToolchainsTests
  build:
    docker:
      - image: codesmithy/gcc-build-prerequisites:0.1.0
    steps:
      - run:
          name: "Set CODESMITHYIDE environment variables"
          command: echo 'export CODESMITHYIDE="/codesmithyide"' >> $BASH_ENV
      - checkout:
          path: /codesmithyide/build-toolchains
      - run:
          name: Build
          command: cd /codesmithyide/build-toolchains/build/GNUmakefile && make
      - run:
          name: Test build
          command: cd /codesmithyide/build-toolchains/Tests/Makefiles/GNUmakefile && make
      - run:
          name: Run the tests
          command: cd /codesmithyide/build-toolchains/Tests/Makefiles/GNUmakefile && ./CodeSmithyBuildToolchainsTests
workflows:
  version: 2
  build:
    jobs:
      - bootstrap-build
      - build
